name: Static analysis
on:
  pull_request:
    paths: [".github/workfloes/*.yml", ".github/workflows/*.yaml"]
defaults:
  run:
    shell: bash
concurrency: # 自動キャンセル
  group: ${{ github.workflow }}-${{ github.ref}}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubntu-latest
    timeout-minutes: 5 # タイムアウト
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker run --rm -v "${pwd}:${pwd}" -w "${pwd}" rhysd/actionlint:latest
